### ISSUE TITLE
Console utility `TypeError: can only concatenate str (not "NoneType") to str`

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/devservices#126]
when performing devservices logs sentry

```
Traceback (most recent call last):
  File "/Users/hubertdeng/code/devservices/.venv/bin/devservices", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hubertdeng/code/devservices/devservices/main.py", line 83, in main
    args.func(args)
  File "/Users/hubertdeng/code/devservices/devservices/commands/logs.py", line 59, in logs
    console.info(log.stdout)
  File "/Users/hubertdeng/code/devservices/devservices/utils/console.py", line 47, in info
    self.print(message=message, color="", bold=bold)
  File "/Users/hubertdeng/code/devservices/devservices/utils/console.py", line 34, in print
    sys.stdout.write(color + message + end + "\n")
```

**Comment by IanWoodard** [comment]
Looks like the stdout was `None` instead of a `str`
